Portfolio setup: Mobile first
SamTush/portfolio pull request #1
Opened 2023-01-13 15:20 UTC by SamTush

##Portfolio setup and mobile-first: add Flexbox

in this project I:

- Add Flexbox for the mobile-first layout.
- Add linter for HTML/CSS.

2023-01-13 18:27 UTC, osamaashraf6 requested changes
Hi @SamTush 😊, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![SoCloseAlmostGIF](https://user-images.githubusercontent.com/83360636/212392288-ceeed3a8-f9b5-4271-9f68-739dfd56c358.gif)

## Highlights
- [x] Good commit messages.✔️
- [x] Descriptive READme file in a professional way.✔️
- [x] No linter errors. ✔️
- [x] Good usage in correcting GitHub flow.✔️
- [x] Nice design.✔️

## Required Changes ♻️

- [ ] You did well 😃 and the linter passed, but Kindly try to resolve the conflict which happened with the pull request💯

## Optional suggestions
- N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-13 18:27 UTC, osamaashraf6 commented on index.html
> +            <nav class="flex-nav box1">
- [x] Great job 😃 on the project, but I see you added a border for the header which not like the Figma design, so kindly try to remove the border from the header to be like the Figma Design💯

| Figma design | Your design| 
| --- | --- |
|   ![image](https://user-images.githubusercontent.com/83360636/212379013-8bfcdbed-90c7-4f5b-b1de-d154103de74c.png)|   ![image](https://user-images.githubusercontent.com/83360636/212378899-61f7893a-d20b-4697-a6d2-86b0f330b202.png) |

2023-01-13 18:27 UTC, osamaashraf6 commented on index.html
> +
- [x] You did well 👌at using the h1 tag for semantics, but I see that you didn't change the color of h1, so please 😊try to change the color of it to be like the Figma Design💯
- [x] Consider trying 😃to use the correct margin-bottom for the h1 ,sos kindly check the Figma design to follow it👌
- [x] Also consider to give the h1 line-height to be like the Figma Design

| Figma design | Your design| 
| --- | --- |
|  ![image](https://user-images.githubusercontent.com/83360636/212381373-aa505de6-ecfa-4a99-a266-534fba3c9ec2.png) |  ![image](https://user-images.githubusercontent.com/83360636/212381441-781c87e9-3d11-4d30-b0c0-54d4854f205c.png)|

2023-01-13 18:27 UTC, osamaashraf6 commented on index.html
> +                    </li>
- [x] Good job 😃, but try to use the correct tags for the semantics reason and user experience, so try to put inside the ```header``` two things the first one is a ```div``` for the logo💯, and inside this div put the logo inside a link ```<a> ``` tag and the second thing is to put ```nav``` tag and inside it the ```ul``` for the links in the future and the hamburger 😊
- [x] Consider remembering to put the correct font size and weight following the Figma design💯

2023-01-13 18:27 UTC, osamaashraf6 commented on index.html
> +                </p>
- [x] Kindly 😊, try to use the correct tag for this part, so please try to use the link ```<a>``` instead of using the p tag here that's for the semantics reason and user experience.💯
- [x] Also consider using the correct font weight, so kindly try to use the correct value following the Figma Design.

| Figma design | Your design| 
| --- | --- |
|   ![image](https://user-images.githubusercontent.com/83360636/212387071-12889d07-4607-4441-8bf7-1bd7ca431dd4.png)|   ![image](https://user-images.githubusercontent.com/83360636/212387205-d9033720-959e-42fb-a51d-9175d78a38dc.png)|

2023-01-13 18:27 UTC, osamaashraf6 commented on index.html
> +                <img src="images/Vector-4.svg" alt="Vector-4" class="icon">
- [x] kindly 😃try to put the correct margin between socials, so it will be better when you follow the Figma design💯
- [x] consider😊 wrapping the images of socials inside a ```<ul>``` tag and every image inside a ```<li>``` tag and inside a li a ```<a>``` tag, so it will be like that ```ul > li > img```👌

| Figma design | Your design| 
| --- | --- |
|   ![image](https://user-images.githubusercontent.com/83360636/212388049-9a2074ad-e47c-45ed-93f4-c1eb4a09f6e0.png) |    ![image](https://user-images.githubusercontent.com/83360636/212388078-e684b4ff-3d47-4631-900b-9696b1a61f03.png) |

2023-01-13 18:27 UTC, osamaashraf6 commented on index.html
> +        <div class="wrapper">
- [ ] Good job👌, but kindly try to use the correct tags for semantics and user experience, so please wrap the logo and the nav links in the future and the hamburger inside the ```<header>``` tag, and the other things which you put it inside a class box2 as p and socials  wrap them inside the ```<section>``` tag 💯

2023-01-13 18:27 UTC, osamaashraf6 commented on index.html
> +
- [ ] Kindly😃, try to remove these tags we will use them later in the other sections.💯

2023-01-13 18:27 UTC, osamaashraf6 commented on index.html
> +                 </p>
- [ ] Great job 😃, but I see that you didn't change the color of the p tag, so kindly try to follow the color for it from the Figma Design 💯
- [ ] Also consider using the font weight of the p tag from the Figma design to let your portfolio look as a professional portfolio👌

| Figma design | Your design| 
| --- | --- |
|   ![image](https://user-images.githubusercontent.com/83360636/212381010-1e762ff6-18c6-4dfa-937b-119c37f3ddbb.png)|    ![image](https://user-images.githubusercontent.com/83360636/212381068-7a71f418-a76f-433b-8388-3421f6a3fff2.png)|

2023-01-14 07:21 UTC, Nyame-Wolf approved these changes
# STATUS: APPROVED :heavy_check_mark: :green_circle: 

Hi @SamTush  :smile: , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![](https://media.giphy.com/media/l4q7TIW8nEZYOJUf6/giphy.gif)


## Highlights :sparkles:
- Used correct gitflow
- Linters passing
- Made changes as requested by reviewer.

## Optional suggestions :ballot_box_with_check: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

APPROVED! 💯 💯 💯

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me, @Nyame-Wolf in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-14 07:23 UTC, merged