Person Portfolio: Desktop version completed.
SamTush/portfolio pull request #6
Opened 2023-01-23 20:11 UTC by SamTush

The complete version of the desktop version.

- develop desktop version to be almost the same as Figma

2023-01-23 21:19 UTC, Gambit142 requested changes
Hi @SamTush 👋, 

Good job so far!

## Highlights
- All linters checks passed ✔️ 
- README.md file is professional ✔️ 
- Used media query between `768` - `1440` px

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please, remember to tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-01-23 21:19 UTC, Gambit142 commented on index.html
>                      <h2>Multi-Post<br>Stories</h2>
- [ ] Kindly follow the design template when designing the header of the cards with the title **_"Multi-Post Stories"_**

### Your Design

![image](https://user-images.githubusercontent.com/77106962/214149442-5d0004ed-4dd7-433d-8470-1cbceab3774f.png)

### Figma Design

![image](https://user-images.githubusercontent.com/77106962/214149558-e83414eb-1244-492b-a541-064590eb5f8d.png)

2023-01-23 21:19 UTC, Gambit142 commented on index.html
>                      <form action="https://formspree.io/f/xvongqly"
- [ ] According to the requirement, the form button should be aligned to the middle on the desktop version but yours is aligned to the left of the form. Kindly implement this requirement. 👍 

### Your Design

![image](https://user-images.githubusercontent.com/77106962/214151427-ee2976b5-cf59-47e2-a4f6-c7ab6f717da3.png)

### Figma Design

![image](https://user-images.githubusercontent.com/77106962/214151552-ee8e17a1-c3d0-439a-828a-5d579a915528.png)

2023-01-24 19:34 UTC, huseyinbiyik approved these changes
Hi @SamTush,

## ✔️ Status: APPROVED 🏆 🎉 🎊

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Alt Text](https://media.giphy.com/media/wZjlCH43M3M0U/giphy.gif)



## Highlights
- Linter set up well and checks pass 🟢
- Github flow followed 👌
- Commit messages are meaningful and written in imperative tense 📝
- Great implementation of the requested changes of previous reviewers 🕸️

## Optional suggestions
[OPTIONAL] Good job with aligning your contact form submit button on desktop. Please make sure your mobile version matches the Figma template design.
<img width="441" alt="Screenshot 2023-01-24 at 10 28 54 PM" src="https://user-images.githubusercontent.com/25887253/214389879-4fe2ba41-a4eb-4922-821f-576c9cb92e5e.png">
<img width="441" alt="Screenshot 2023-01-24 at 10 29 55 PM" src="https://user-images.githubusercontent.com/25887253/214390062-3f791845-d348-4e9f-8c30-8b0e19e03b98.png">

[OPTIONAL] Please make sure your website is responding to different sizes. When you change the screen width there are some parts breaking, nav is not extending etc. Check the gif below.
![Screen Recording 2023-01-24 at 10 19 41 PM](https://user-images.githubusercontent.com/25887253/214390418-84b843bc-0e17-4943-9c07-8b4eb0e4ecc4.gif)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-25 09:55 UTC, merged